
service: emptor # NOTE: update this with your service name
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
        - "s3:*"
      Resource:
        - "*"

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true

functions:
  get_page_title_handler:
    handler: handler.get_page_title_handler
    name: ${self:provider.stage}-getPageTitle
    description: Lambda function to get a page title from a given url

# you can add CloudFormation resource templates here
resources:
  Resources:
    EmptorUrlDynamodbTable:
      Type: AWS:DynamoDB::Table
      Properties:
        TableName: UrlDocument
        AttributeDefinitons:
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: title
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    EmptorUrlS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: url-bucket-1047