
service: emptor

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
        - "s3:*"
      Resource:
        - "*"

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true

functions:
  get_page_title_handler:
    handler: handler.get_page_title_handler
    name: ${self:provider.stage}-getPageTitle
    description: Lambda function to get a page title from a given url
  create_request_identifier_handler:
    handler: handler.create_request_identifier_handler
    name: ${self:provider.stage}-createReqIdentifier
    description: Lambda function to create a request identifier


resources:
  Resources:
    EmptorUrlDynamodbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UrlDocument
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: url
            AttributeType: S
          - AttributeName: state
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    EmptorUrlS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: url-bucket-1047
